# Introdução a Ciência de Dados

## Semana 2 - Exercícios

Aluno: Thiago William P. Sousa
Prof. Dr. Eduardo Santarem

### Exercícios propostos


1. Carregue as bibliotecas NumPy e Pandas.
2. Crie um NDArray com os seguintes valores [1, 2.5, 7, -78, -0.9, 130, 25].
3. Crie um NDArray com os valores de 0 a 10.
4. Crie um NDArray de dimensão 2x5 com valores 1.
5. Crie um NDArray com valores de 1 a 100, com intervalos de 3 em 3.
6. Mostre as raízes quadradas dos valores do NDArray criado no exercício 5.
7. Altere a décima posição do NDArray criado no exercício 5 com o dobro do seu valor.
8. Execute o comando para criar um DataFrame com os dados disponíveis no notebook.

dados={'Empresa':['Microsoft', 'Google','Univesp','NVData Analytics','Power Bi Experience','USP'], 'Qtde Func':[1000, 1500,500, 100,100,499], 'Site':['https://www.microsoft.com/pt-br','https://www.google.com/','https://univesp.br/','https://www.nvdata.com.br/','https://powerbiexperience.com/pt/','https://www.usp.br/'],'Instagram':['@microsoft','@google','@univespoficial','@nv_data','@leokarpa','@usp.oficial'],'Criação':[1975,1998,2012,2019,2016,1934], 'País':['EUA','EUA','Brasil','Brasil','Brasil','Brasil']}

9. Execute um comando que seja possível identificar qual a média da quantidade de funcionários que as empresas listadas têm. Informe também a soma dos funcionários que as empresas têm.
10. Mostre as primeiras 3 linhas do DataFrame.
11. Mostre as últimas 3 linhas do DataFrame.
12. Liste apenas as linhas em que as empresas foram criadas nos últimos 10 anos. Informe a quantidade de registros.
13. Vamos imaginar que em todas as empresas exista 1 chefe para cada 23 funcionários. Crie uma coluna que mostre a quantidade de chefes que cada empresa teria, depois informe quantos chefes teríamos ao todo. (os valores não precisam ser números inteiros, é apenas uma estimativa).



In [7]:
#1

import numpy as np
import pandas as pd

In [8]:
# 2

array1 = np.array([1, 2.5, 7, -78, -0.9, 130, 25])

In [15]:
# 3

array2 = np.arange(11)
print(array2)


[ 0  1  2  3  4  5  6  7  8  9 10]


In [18]:
# 4

array3 = np.ones((2,5))
print(array3)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [21]:
# 5

array4 = np.arange(1,100,3)
print(array4)

[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49 52 55 58 61 64 67 70
 73 76 79 82 85 88 91 94 97]


In [22]:
# 6

np.sqrt(array4)

array([1.        , 2.        , 2.64575131, 3.16227766, 3.60555128,
       4.        , 4.35889894, 4.69041576, 5.        , 5.29150262,
       5.56776436, 5.83095189, 6.08276253, 6.32455532, 6.55743852,
       6.78232998, 7.        , 7.21110255, 7.41619849, 7.61577311,
       7.81024968, 8.        , 8.18535277, 8.36660027, 8.54400375,
       8.71779789, 8.88819442, 9.05538514, 9.21954446, 9.38083152,
       9.53939201, 9.69535971, 9.8488578 ])

In [24]:
# 7
array4 = array4[9]*2

In [25]:
#8

dados={'Empresa':['Microsoft', 'Google','Univesp','NVData Analytics','Power Bi Experience','USP'], 'Qtde Func':[1000, 1500,500, 100,100,499], 'Site':['https://www.microsoft.com/pt-br','https://www.google.com/','https://univesp.br/','https://www.nvdata.com.br/','https://powerbiexperience.com/pt/','https://www.usp.br/'],'Instagram':['@microsoft','@google','@univespoficial','@nv_data','@leokarpa','@usp.oficial'],'Criação':[1975,1998,2012,2019,2016,1934], 'País':['EUA','EUA','Brasil','Brasil','Brasil','Brasil']}

df1 = pd.DataFrame(dados)
df1

Empresa  Qtde Func                               Site  \
0            Microsoft       1000    https://www.microsoft.com/pt-br   
1               Google       1500            https://www.google.com/   
2              Univesp        500                https://univesp.br/   
3     NVData Analytics        100         https://www.nvdata.com.br/   
4  Power Bi Experience        100  https://powerbiexperience.com/pt/   
5                  USP        499                https://www.usp.br/   

         Instagram  Criação    País  
0       @microsoft     1975     EUA  
1          @google     1998     EUA  
2  @univespoficial     2012  Brasil  
3         @nv_data     2019  Brasil  
4        @leokarpa     2016  Brasil  
5     @usp.oficial     1934  Brasil

In [29]:
# 9

df1.describe()

Qtde Func      Criação
count     6.000000     6.000000
mean    616.500000  1992.333333
std     545.631286    32.843061
min     100.000000  1934.000000
25%     199.750000  1980.750000
50%     499.500000  2005.000000
75%     875.000000  2015.000000
max    1500.000000  2019.000000

In [34]:
sum(df1['Qtde Func'])

3699

In [30]:
# 10

df1.head(3)

Empresa  Qtde Func                             Site        Instagram  \
0  Microsoft       1000  https://www.microsoft.com/pt-br       @microsoft   
1     Google       1500          https://www.google.com/          @google   
2    Univesp        500              https://univesp.br/  @univespoficial   

   Criação    País  
0     1975     EUA  
1     1998     EUA  
2     2012  Brasil

In [31]:
# 11

df1.tail(3)

Empresa  Qtde Func                               Site  \
3     NVData Analytics        100         https://www.nvdata.com.br/   
4  Power Bi Experience        100  https://powerbiexperience.com/pt/   
5                  USP        499                https://www.usp.br/   

      Instagram  Criação    País  
3      @nv_data     2019  Brasil  
4     @leokarpa     2016  Brasil  
5  @usp.oficial     1934  Brasil

In [33]:
# 12

df1[df1['Criação'] >= 2014]

Empresa  Qtde Func                               Site  \
3     NVData Analytics        100         https://www.nvdata.com.br/   
4  Power Bi Experience        100  https://powerbiexperience.com/pt/   

   Instagram  Criação    País  
3   @nv_data     2019  Brasil  
4  @leokarpa     2016  Brasil

In [36]:
# 13

df1['Qtd Chefes'] = df1['Qtde Func']/23
df1

Empresa  Qtde Func                               Site  \
0            Microsoft       1000    https://www.microsoft.com/pt-br   
1               Google       1500            https://www.google.com/   
2              Univesp        500                https://univesp.br/   
3     NVData Analytics        100         https://www.nvdata.com.br/   
4  Power Bi Experience        100  https://powerbiexperience.com/pt/   
5                  USP        499                https://www.usp.br/   

         Instagram  Criação    País  Qtd Chefes  
0       @microsoft     1975     EUA   43.478261  
1          @google     1998     EUA   65.217391  
2  @univespoficial     2012  Brasil   21.739130  
3         @nv_data     2019  Brasil    4.347826  
4        @leokarpa     2016  Brasil    4.347826  
5     @usp.oficial     1934  Brasil   21.695652

In [37]:
df1['Qtd Chefes'].sum()

160.82608695652175